// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
    public static void main(String[] args) {
        int reps = Integer.parseInt(args[0]);
        double rand = 0;
        int aboveHalf = 0;
        int belowHalf = 0;
        double ratio = 0.0;
        for (int i = 0; i < reps; i++) {
            rand = Math.random();
            if (rand > 0.5)
                aboveHalf++;
            else
                belowHalf++;
        }
        if (belowHalf == 0)
            ratio = 1.0;
        else
            ratio = (double) aboveHalf / belowHalf;
        System.out.println("> 0.5: " + aboveHalf + " times");
        System.out.println("<= 0.5: " + belowHalf + " times");
        System.out.println("Ratio: " + ratio);
    }
}
